### ISSUE TITLE
ImportError: No module named frame3dd

### ISSUE THREAD

**Issue by zahmed80** [WISDEM/pyFrame3DD#1]
I installed as you explained, but i get this error when i run the test_frame.py

ImportError: No module named frame3dd

**Comment by jarvisoac** [comment]
Change 

`from frame3dd import Frame, NodeData, ReactionData, ElementData, Options, StaticLoadCase`

to 

`from pyframe3dd import Frame, NodeData, ReactionData, ElementData, Options, StaticLoadCase`

may solve the problem.
