### ISSUE TITLE
install with pip

### ISSUE THREAD

**Issue by plyd** [WISDEM/pyFrame3DD#2]
Hello,

Thanks for updating pyFrame3DD!

I used to install pyFrame3dd with pip like this:
pip install git+http://github.com/WISDEM/pyFrame3DD.git@master#egg=pyFrame3DD
But it does not install frame3dd.py anymore. Something I could do? (except going back to commit 680a8ba1b00b45ad6f76a76374f2b83cfb3c56df )

Vincent

**Comment by dykesk** [comment]
@gbarter I think you addressed this?

**Comment by gbarter** [comment]
Hello @plyd 

Yes, this functionality was temporarily broken and I apologize.  The most recent commits should have resolved the issue.
