### ISSUE TITLE
name of the module in ""setup.py"

### ISSUE THREAD

**Issue by gx1333** [WISDEM/pyFrame3DD#4]
Hi, there,

I'm trying to import your package into our internal usage, while my company request that all package name follow the PEP8: https://www.python.org/dev/peps/pep-0008/#package-and-module-names. 
Do you think it is possible for the name of the package changed to "pyframe3dd"?

Thanks so much for the consideration.

**Comment by gbarter** [comment]
Very sorry for the long delay on this.  This is a good suggestion.  I have made the change.
