### ISSUE TITLE
unresolved external symbol _D3matrix

### ISSUE THREAD

**Issue by ceanwang** [WISDEM/pyFrame3DD#5]
Hi,

Tried to install pyFrame3DD on win 10 pro. I have installed MS VS 2017, numpy and pyMAP. 

When install pyFrame3DD, got 4 unresolved externals. py_main.obj has two _D3matrix, py_frame3dd.obj has two _free_D3matrix.

Same error as this : https://github.com/WISDEM/pyFrame3DD/issues/1

What else I need to install?

Regards,

Cean

**Comment by jarvisoac** [comment]
Please add this line to NRutil.h:53

`#define ANSI  1`

just before

`#if defined(__STDC__) || defined(ANSI) || defined(NRANSI)`

Assuming you are compiling on Windows with Visual Studio (mine is VS 2017).

**Comment by ceanwang** [comment]
It works. Thank you very much.
